# Generated by Django 4.1.1 on 2023-03-03 02:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('password_confirmation', models.CharField(max_length=30, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=13, null=True, region='UZ')),
                ('telegram', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='media/user_loaded_images')),
                ('brand_name', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media/user_loaded_images')),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('orders', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('books_ordered', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_legal_entity', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(null=True)),
                ('date_joined', models.DateField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
