from django.contrib import admin
from .models import *

admin.site.register(Book)
admin.site.register(Order)
admin.site.register(Complaint)
admin.site.register(News)
admin.site.register(Contact)
admin.site.register(CreateSite)
admin.site.register(BlogPost)
admin.site.register(OrderOptions)
admin.site.register(Account)
admin.site.register(CategoryEx)
admin.site.register(CategoryIn)
admin.site.register(SubCategoryEx)
admin.site.register(SubCategoryIn)
admin.site.register(Expense)
admin.site.register(Income)
admin.site.register(Transaction)
admin.site.register(LType)
admin.site.register(Loss)
admin.site.register(RType)
admin.site.register(Resource)
