from django.contrib import admin
from .models import *

admin.site.register(Book)
admin.site.register(Order)
admin.site.register(Complaint)
admin.site.register(News)
admin.site.register(Contact)
admin.site.register(BlogPost)
admin.site.register(OrderOptions)
admin.site.register(Account)
admin.site.register(CategoryEx)
admin.site.register(CategoryIn)
admin.site.register(SubCategoryEx)
admin.site.register(SubCategoryIn)
admin.site.register(Expense)
admin.site.register(Income)
admin.site.register(Transaction)
admin.site.register(LType)
admin.site.register(Loss)
admin.site.register(RType)
admin.site.register(Resource)
admin.site.register(OuterPrice)
admin.site.register(BindingPrice)
admin.site.register(RingPrice)
admin.site.register(ColorPrice)
admin.site.register(CoverPrice)
admin.site.register(GluePrice)
admin.site.register(PagePrice)
admin.site.register(PaperPrice)
admin.site.register(YarnPrice)
admin.site.register(Workforce)
admin.site.register(Printer)
admin.site.register(RefillAndPageCount)
admin.site.register(Coupon)
