# Generated by Django 4.1.1 on 2022-09-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chars',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_loaded_images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UZS', max_digits=12),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('place_to_get', models.CharField(choices=[('KA', 'Kamandi'), ('GL', "Eski Ko'z kasalliklari shifoxonasi"), ('II', 'Irrigatsiya instituti')], max_length=2)),
                ('customer_number', models.CharField(max_length=14)),
                ('customer_email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('payment', models.CharField(choices=[('CL', 'Click'), ('CSH', 'Naqd'), ('V', 'VISA')], max_length=3)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_loaded_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='CreateSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('m_name', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.IntegerField(default=18)),
                ('person', models.CharField(choices=[('JS', 'Jismoniy shaxs'), ('YS', 'Yuridik shaxs')], max_length=2)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('mail', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('client_number', models.IntegerField(default=None)),
                ('site_description', models.CharField(max_length=400)),
                ('country', models.CharField(choices=[('KG', "Qirg'iziston"), ('KZ', "Qozog'iston"), ('RU', 'Rossiya'), ('TJ', 'Tojikiston'), ('TM', 'Turkmaniston'), ('UZ', "O'zbekiston")], max_length=2)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('time_bought', models.DateField()),
                ('problem', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.book')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
