# Generated by Django 4.1.1 on 2022-09-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_book_chars_book_picture_alter_book_price_order_news_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.book'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='time_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
