# Generated by Django 4.1.1 on 2022-09-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='static/user_loaded_images/open.png', null=True, upload_to='user_loaded_images/'),
        ),
    ]
