# Generated by Django 4.1.1 on 2022-09-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_news_article_remove_news_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('F', 'Fantastika'), ('SF', 'Ilmiy Fantastika'), ('CF', 'Zamonaviy Fantastika'), ('HF', 'Tarixiy Fantastika'), ('AA', 'Sarguzashtlar'), ('M', 'Detektiv'), ('R', 'Romantika'), ('N', 'Romanlar'), ('SS', 'Qisqa hikoyalar'), ('DS', 'Aniq fanlar'), ('L', 'Tilga oid'), ('P', 'Axborot Texnologiyalariga oid')], default=None, max_length=2, null=True),
        ),
    ]
