# Generated by Django 4.1.1 on 2022-09-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('DS', 'Aniq fanlar'), ('P', 'Axborot Texnologiyalariga oid'), ('M', 'Detektiv'), ('F', 'Fantastika'), ('SF', 'Ilmiy Fantastika'), ('SS', 'Qisqa hikoyalar'), ('N', 'Romanlar'), ('R', 'Romantika'), ('AA', 'Sarguzashtlar'), ('HF', 'Tarixiy Fantastika'), ('L', 'Tilga oid'), ('CF', 'Zamonaviy Fantastika')], default=None, max_length=2, null=True),
        ),
    ]
