# Generated by Django 4.1.1 on 2022-09-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/'),
        ),
    ]
