# Generated by Django 4.1.1 on 2022-09-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/user_loaded_images/'),
        ),
    ]
