# Generated by Django 4.1.1 on 2022-09-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_news_picture_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('Click', 'Click'), ('Naqd', 'Naqd'), ('VISA', 'VISA')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_to_get',
            field=models.CharField(choices=[('Kamandi MFY', 'Kamandi MFY'), ("Eski Ko'z kasalliklari shifoxonasi", "Eski Ko'z kasalliklari shifoxonasi"), ('Qarshi Muhandislik-Iqtisodiyot Instituti', 'Qarshi Muhandislik-Iqtisodiyot Instituti')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[("To'lovni kutmoqda", "To'lovni kutmoqda"), ('Qabul qilindi', 'Qabul qilindi'), ('Chop etilmoqda', 'Chop etilmoqda'), ('Tayyor', 'Tayyor')], default='TK', max_length=50, null=True),
        ),
    ]
