# Generated by Django 4.1.1 on 2022-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_order_payment_alter_order_place_to_get_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createsite',
            name='country',
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Aniq fanlar', 'Aniq fanlar'), ('Axborot Texnologiyalariga oid', 'Axborot Texnologiyalariga oid'), ('Detektiv', 'Detektiv'), ('Fantastika', 'Fantastika'), ('Ilmiy Fantastika', 'Ilmiy Fantastika'), ('Qisqa hikoyalar', 'Qisqa hikoyalar'), ('Romanlar', 'Romanlar'), ('Romantika', 'Romantika'), ('Sarguzashtlar', 'Sarguzashtlar'), ('Tarixiy Fantastika', 'Tarixiy Fantastika'), ('Tilga oid', 'Tilga oid'), ('Zamonaviy Fantastika', 'Zamonaviy Fantastika')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createsite',
            name='person',
            field=models.CharField(blank=True, choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='user_loaded_images/'),
        ),
    ]
