# Generated by Django 4.1.1 on 2022-09-28 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0015_remove_createsite_country_alter_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publisher_tw',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subtitle_1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subtitle_2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('subtitle_3', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('picture_1', models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/')),
                ('picture_2', models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/')),
                ('picture_3', models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/')),
                ('body_1', models.TextField(blank=True, default=None, null=True)),
                ('body_2', models.TextField(blank=True, default=None, null=True)),
                ('body_3', models.TextField(blank=True, default=None, null=True)),
                ('conclusion', models.TextField(blank=True, default=None, null=True)),
                ('publisher_tg', models.URLField(blank=True, default=None, null=True)),
                ('publisher_li', models.URLField(blank=True, default=None, null=True)),
                ('publisher_gm', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('publisher_tw', models.URLField(blank=True, default=None, null=True)),
                ('ref_links', models.TextField(blank=True, default=None, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
