# Generated by Django 4.1.1 on 2022-10-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_blogpost_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
