# Generated by Django 4.1.1 on 2022-10-01 09:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0019_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_sum',
        ),
        migrations.AddField(
            model_name='book',
            name='telegram_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='UZ'),
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='back_cover_color',
            field=models.CharField(blank=True, choices=[("Ko'k", "Ko'k"), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='book_type',
            field=models.CharField(blank=True, choices=[('Plastik prujinalangan', 'Plastik prujinalangan'), ('Metal prujinalangan', 'Metal prujinalangan'), ('Yelimlangan yumshoq muqovali', 'Yelimlangan yumshoq muqovali'), ('Yelimlangan qattiq muqovali', 'Yelimlangan qattiq muqovali')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_book',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='front_cover_color',
            field=models.CharField(blank=True, choices=[("Ko'k", "Ko'k"), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ring_color',
            field=models.CharField(blank=True, choices=[("Ko'k", "Ko'k"), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_needs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createsite',
            name='client_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UZ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region='UZ'),
        ),
    ]
