# Generated by Django 4.1.1 on 2022-10-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_orderoptions_remove_complaint_custom_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoptions',
            options={'verbose_name': 'OrderOptions', 'verbose_name_plural': 'OrderOptions'},
        ),
    ]
