# Generated by Django 4.1.1 on 2022-10-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_orderoptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderoptions',
            options={'verbose_name': 'Order Options', 'verbose_name_plural': 'Order Options'},
        ),
    ]
