# Generated by Django 4.1.1 on 2022-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_orderoptions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='back_cover_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], default='Ko`k', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='front_cover_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], default='Ko`k', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ring_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], default='Ko`k', max_length=100, null=True),
        ),
    ]
