# Generated by Django 4.1.1 on 2022-10-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_alter_order_back_cover_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chars',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='back_cover_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='front_cover_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='place_to_get',
            field=models.CharField(choices=[('Qarshi Muhandislik-Iqtisodiyot Instituti', 'Qarshi Muhandislik-Iqtisodiyot Instituti'), ('Kamandi MFY', 'Kamandi MFY')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ring_color',
            field=models.CharField(blank=True, choices=[('Ko`k', 'Ko`k'), ('Qizil', 'Qizil'), ('Qora', 'Qora'), ('Rangsiz', 'Rangsiz'), ('Sariq', 'Sariq'), ('Yashil', 'Yashil')], max_length=100, null=True),
        ),
    ]
