# Generated by Django 4.1.1 on 2022-10-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_alter_book_chars_alter_order_back_cover_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price_currency',
        ),
        migrations.AddField(
            model_name='createsite',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[("To'lovni kutmoqda", "To'lovni kutmoqda"), ('Bekor qilindi', 'Bekor qilindi'), ('Qabul qilindi', 'Qabul qilindi'), ('Chop etilmoqda', 'Chop etilmoqda'), ('Tayyor', 'Tayyor')], default="To'lovni kutmoqda", max_length=50, null=True),
        ),
    ]
