# Generated by Django 4.1.1 on 2022-10-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_remove_book_price_remove_book_price_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
