# Generated by Django 4.1.1 on 2022-10-06 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0027_contact_date_made'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True)),
                ('means_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3)),
                ('means', djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'ExCategory',
                'verbose_name_plural': 'ExCategories',
            },
        ),
        migrations.CreateModel(
            name='CategoryIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'InCategory',
                'verbose_name_plural': 'InCategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryEx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'ExSubcategory',
                'verbose_name_plural': 'ExSubcategories',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.CharField(default=None, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'InSubcategory',
                'verbose_name_plural': 'InSubcategories',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_1',
            field=models.ImageField(default='user_loaded_images', null=True, upload_to='user_loaded_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_2',
            field=models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture_3',
            field=models.ImageField(blank=True, default='user_loaded_images', null=True, upload_to='user_loaded_images/'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(default=None, null=True)),
                ('comment', models.TextField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.categoryin')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcategoryin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_made', models.DateTimeField(default=None, null=True)),
                ('comment', models.TextField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.account')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.categoryex')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcategoryex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
