# Generated by Django 4.1.1 on 2022-10-08 03:43

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_account_categoryex_categoryin_subcategoryex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='means',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='means_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True)),
                ('amount', djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.account')),
            ],
        ),
    ]
