# Generated by Django 4.1.1 on 2022-10-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_expense_amount_currency_income_amount_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='accounts',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acc_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_1', to='service.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='acc_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_2', to='service.account'),
        ),
    ]
