# Generated by Django 4.1.1 on 2022-10-11 10:52

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_remove_transaction_accounts_transaction_acc_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='changed_amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='changed_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='changed_amount',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='changed_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_made',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
