# Generated by Django 4.1.1 on 2022-10-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_expense_changed_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='changed_amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='changed_amount_currency',
        ),
        migrations.RemoveField(
            model_name='income',
            name='changed_amount',
        ),
        migrations.RemoveField(
            model_name='income',
            name='changed_amount_currency',
        ),
    ]
