# Generated by Django 4.1.1 on 2022-10-12 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0032_remove_expense_changed_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('ptype', models.CharField(blank=True, max_length=15, null=True)),
                ('sheets', models.IntegerField(blank=True, null=True)),
                ('packs', models.IntegerField(blank=True, null=True)),
                ('boxes', models.IntegerField(blank=True, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('gram', models.IntegerField(blank=True, null=True)),
                ('bottles', models.IntegerField(blank=True, null=True)),
                ('time_bought', models.DateField(null=True)),
                ('worth_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], default='UZS', editable=False, max_length=3, null=True)),
                ('worth', djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR'), ('RUB', 'RUB'), ('USD', 'USD'), ('UZS', 'UZS')], decimal_places=2, default_currency='UZS', max_digits=50, null=True)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('amount_used', models.IntegerField(blank=True, null=True)),
                ('available', models.BooleanField(default=True, null=True)),
                ('rtype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.rtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('ptype', models.CharField(blank=True, max_length=15, null=True)),
                ('sheets', models.IntegerField(blank=True, null=True)),
                ('packs', models.IntegerField(blank=True, null=True)),
                ('boxes', models.IntegerField(blank=True, null=True)),
                ('pieces', models.IntegerField(blank=True, null=True)),
                ('gram', models.IntegerField(blank=True, null=True)),
                ('bottles', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('time_loss', models.DateField(null=True)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('ltype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.ltype')),
            ],
            options={
                'verbose_name': 'Loss',
                'verbose_name_plural': 'Losses',
            },
        ),
    ]
