# Generated by Django 4.1.1 on 2022-10-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_alter_resource_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltype',
            name='color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ltype',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rtype',
            name='color',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rtype',
            name='size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
